language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements_dev.txt
# command to run tests
script: pytest
# command to format code
after_sucess: black . && codespell --skip=".git,*.gif,*.png,*.PNG,./venv,*.json,./datasets,.DS_Store,*.pyc"
